name = "CodeEvaluation"
uuid = "5a076611-96cb-4f02-9d3a-9e309f06f8ff"
authors = ["Morten Piibeleht <morten.piibeleht@juliahub.com> and contributors"]
version = "0.0.1"

[deps]
#Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
IOCapture = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
